### PR TITLE
Registration

### PR DESCRIPTION
**Pull request by JinmingYu**

### CODE REVIEW

**Comment by crasm** [comment]
Are you able to run the activity? I don't see a way to access it through the app.

**Comment by crasm** [comment]
This is for issue #2.

**Comment by JinmingYu** [comment]
i usually run it after changing manifast file. I do not know where we are going to start it so I did not add the intent to registration.

**Review by crasm — CHANGES_REQUESTED** [review]
Can you add a way to launch registration or login from the maps activity?

Also, please make sure to run the "checks" I mentioned in slack since there were some things it found.

**Comment by crasm** [comment]
Were you able to pass the checks?

**Pull request closed without merging**
